version: 2

models:
  - name: daily_customer_orders_success
    columns:
      - name: state_name
      - name: total_orders
  - name: monthly_sales
    columns:
      - name: month
      - name: total
  - name: daily_sales
    columns:
      - name: day
      - name: total
sources:
  - name: tutorial
    description: 'Customer records warehouse'
    database: tutorial
    schema: dbt_tutorial
    tables:
      - name: customer_orders
      - name: customer
      - name: orders
